### ISSUE TITLE
Drop table merge strategy is faulty or unclear

### ISSUE THREAD

**Issue by jordanbtucker** [NiceneNerd/BCML#160]
I'm the author of the mod [No Loot Boxes](https://gamebanana.com/mods/290840), which modifies the amiibo drop tables to ensure that amiibo chests contain exclusive items. A recent comment asked if mods like [Standalone Sacred Bow](https://gamebanana.com/mods/49694) are compatible with No Loot Boxes. As I guessed, they are not compatible because Standalone Sacred Bow adds a new item with its own ID to the game and modifies the drop tables of the Skyward Sword Link amiibo so that it drops the bow. However, the way that BCML merges the drop tables surprised me.

I would have expected that one of the drop tables would just overwrite the other one, depending on the priority. However, it appears that BCML attempts to merge the two drop tables into something that doesn't really make sense to me.

Here's what a section of the Skyward Sword Link amiibo drop table looks like in the No Loot Boxes BNP:

```
    "BigHit(Remain)": {
      "repeat_num_min": 1,
      "repeat_num_max": 1,
      "approach_type": 0,
      "occurrence_speed_type": 0,
      "items": {
        "Armor_215_Head": 25.0,
        "Armor_215_Upper": 25.0,
        "Armor_215_Lower": 25.0,
        "Weapon_Sword_057": 25.0
      }
    },
```

Notice that it completely replaces the vanilla drop table for common chest items with only exclusive items normally received from a rare chest drop after completing at least one Divine Beast.

Now compare that to the same section from Standalone Sacred Bow:

```
    "BigHit(Remain)": {
      "repeat_num_min": 1,
      "repeat_num_max": 1,
      "approach_type": 0,
      "occurrence_speed_type": 0,
      "items": {
        "Obj_FireArrow_A_03": "UNDERRIDE_CONST",
        "Obj_IceArrow_A_03": "UNDERRIDE_CONST",
        "Obj_ElectricArrow_A_03": "UNDERRIDE_CONST",
        "Obj_BombArrow_A_02": "UNDERRIDE_CONST",
        "Weapon_Shield_002": "UNDERRIDE_CONST",
        "Weapon_Sword_002": "UNDERRIDE_CONST"
      }
    },
```

Notice that Standalone Sacred Bow does not modify this section at all. This is the same as the vanilla drop table.

But this is what BCML actually merges everything into when No Loot Boxes is given higher priority:

```yml
    BigHit(Remain): !obj
      RepeatNumMin: 1
      RepeatNumMax: 1
      ApproachType: 0
      OccurrenceSpeedType: 0
      ColumnNum: 10
      ItemName01: !str64 Obj_FireArrow_A_03
      ItemProbability01: 15.0
      ItemName02: !str64 Obj_IceArrow_A_03
      ItemProbability02: 15.0
      ItemName03: !str64 Obj_ElectricArrow_A_03
      ItemProbability03: 15.0
      ItemName04: !str64 Obj_BombArrow_A_02
      ItemProbability04: 15.0
      ItemName05: !str64 Weapon_Shield_002
      ItemProbability05: 20.0
      ItemName06: !str64 Weapon_Sword_002
      ItemProbability06: 20.0
      ItemName07: !str64 Armor_215_Head
      ItemProbability07: 25.0
      ItemName08: !str64 Armor_215_Upper
      ItemProbability08: 25.0
      ItemName09: !str64 Armor_215_Lower
      ItemProbability09: 25.0
      ItemName10: !str64 Weapon_Sword_057
      ItemProbability10: 25.0
```

BCML has included all items from both drop tables, and the probabilities no longer add up to 100. Now, I could understand this behavior if Standalone Sacred Bow actually modified this section of the drop table, but it leaves it untouched, so having it interfere with No Loot Boxes is confusing.

I'm not sure what the best solution for this problem is, but as it is now, there doesn't seem to be a way to make No Loot Boxes compatible with Standalone Sacred Bow because they both modify the same drop tables, and neither can overwrite the other.
